version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    platform: linux/arm64
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: .
      dockerfile: Dockerfile.client

  postgres:
    image: postgres:16.2-alpine
    platform: linux/arm64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata16:/var/lib/postgresql/data
    networks:
      - pg_net

  redis:
    image: redis:alpine
    platform: linux/arm64
    ports:
      - "6379:6379"

volumes:
  pgdata16:

networks:
  pg_net:
