version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: .
      dockerfile: Dockerfile.client

  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: tankuser
      POSTGRES_PASSWORD: tankpassword
      POSTGRES_DB: tankgame
    volumes:
      - pgdata16:/var/lib/postgresql/data
    networks:
      - pg_net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata16:

networks:
  pg_net:
